/** Nationalités au féminin (usage licence joueur). */
export const NATIONALITIES = [
  "Camerounaise",
  "Algérienne",
  "Angolaise",
  "Béninoise",
  "Burkinabè",
  "Burundaise",
  "Centrafricaine",
  "Comorienne",
  "Congolaise (RDC)",
  "Congolaise (RC)",
  "Ivoirienne",
  "Djiboutienne",
  "Égyptienne",
  "Érythréenne",
  "Éthiopienne",
  "Gabonaise",
  "Gambienne",
  "Ghanéenne",
  "Guinéenne",
  "Guinéenne-Bissau",
  "Guinéenne équatoriale",
  "Kényane",
  "Libérienne",
  "Libyenne",
  "Malagasy",
  "Malawite",
  "Malienne",
  "Marocaine",
  "Mauricienne",
  "Mauritanienne",
  "Mozambicaine",
  "Namibienne",
  "Nigérienne",
  "Nigériane",
  "Ougandaise",
  "Rwandaise",
  "Sénégalaise",
  "Sierra-Léonaise",
  "Somalienne",
  "Soudanaise",
  "Sud-Africaine",
  "Sud-Soudanaise",
  "Tanzanienne",
  "Tchadienne",
  "Togolaise",
  "Tunisienne",
  "Zambienne",
  "Zimbabwéenne",
  "Française",
  "Belge",
  "Suisse",
  "Allemande",
  "Espagnole",
  "Italienne",
  "Portugaise",
  "Anglaise",
  "Brésilienne",
  "Argentine",
  "Autre",
] as const;

export const DEFAULT_NATIONALITY = "Camerounaise";

export type Nationality = (typeof NATIONALITIES)[number];
